kblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("posts.urls", namespace='posts')),
] + staticfiles_urlpatterns()

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.posts_list, name="list"),
    url(r'^create/$', views.posts_create, name="create"),
    url(r'^about/$', views.about, name="about"),
    url(r'^(?P<slug>[\w-]+)/$', views.posts_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.posts_update, name="edit"),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.posts_delete, name="delete"),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    content = models.TextField(null=True, blank=True)
    imageurl = models.URLField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug":self.slug})

    class Meta:
        ordering = ["-id","-timestamp", "-updated"]



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_reciever, sender=Post)

posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "imageurl"
        ]

posts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Post
from .forms import PostForm
# Create your views here.

def posts_list(request):
    #return HttpResponse("<h1>list</h1>")
    queryset_list = Post.objects.all()
    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
    "objlist" : queryset
    }
    return render(request, "postlist.html", context)


def posts_create(request):
    if not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form
    }
    return render(request, "postcreate.html", context)


def posts_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    context = {
        "instance" : instance
    }
    return render(request, "postdetail.html", context)

def posts_update(request, slug=None):
    if not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "instance" : instance,
        "form": form,
    }
    return render(request, "postedit.html", context)

def posts_delete(request, slug=None):
    if not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")

def about(request):
    context = {}
    return render(request, "about.html", context)

templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}

<link rel="stylesheet" type="text/css" media="all" href="{% static 'galery/css/styles.css' %}">
<link rel="stylesheet" type="text/css" media="all" href="{% static 'galery/css/magnific-popup.css' %}">
<script type="text/javascript" src="{% static 'galery/js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'galery/js/jquery.magnific-popup.min.js' %}"></script>

{% endblock head %}

{% block content %}

<header class="intro-header" style="background-color: #f28281;">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading" style="padding-top:100px;padding-bottom:100px">
                    <h1>Killer Kulbeer <i class="fa fa-heart" aria-hidden="true"></i></h1>
                </div>
            </div>
        </div>
    </div>
</header>


<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
            		<img src="{% static 'img/4.jpg' %}" style="display:block;height:100%;width:100%;padding-left:;" />
            </div>
            <div class="col-sm-8" style="font-size:145%">
            		Hi! I am Kulbeer (<strong> pixy </strong> is what my friends call me).I am MCA student and a part time writter.
                Taking selfies, listing to music, shopping are some of my labors of love. I am clumsy as hell! I have deep love for
                dogs and good food. And I am a die hard chocoholic.
                <br>
                My lifestyle, which isn't necessarily perfect, but it makes me happy. Now while my grammar and punctuation might not always
                be perfect , I love to write. I plan on posting from shayaris and quotes to short stories.

           </div>

        </div>
        <hr>

      </div>
</section>
  <section style="background-color:rgb(188, 162, 230)">
      <div class="container" >
        <div class="row" >
            <div class="col-sm-7" style="font-size:135%">
              <br><br><br><br>
            <blockquote style="font-size:135%;color:white;">"Every verse I create, creates me.<br>
            I write to create myself."</blockquote>
            </div>
            <div class="col-sm-5" style="font-size:135%">
            		<img src="{% static 'img/123.jpg' %}" style="display:block;height:100%;width:100%;padding-top:10px;padding-bottom:10px" />
           </div>

        </div>
      </div>
    </div>
</section>

<!-- Photo Grid Section -->

<div id="wrapper">
    <h1 style="text-align: center;">My Life In Images</h1>

    <ul id="portfolio" class="clearfix">
      <li><a href="{% static 'galery/img/item01@2x.jpg' %}" title="Brick and Bay Windows"><img src="{% static 'galery/img/item01.jpg' %}" alt="brick and by windows" style="border: 0; max-width: 100%;"></a></li>
      <!-- https://dribbble.com/shots/1543255-Brick-and-Bay-Windows -->

      <li><a href="{% static 'galery/img/item02@2x.jpg' %}" title="Simple iPad Icons"><img src="{% static 'galery/img/item02.jpg' %}" alt="old-style ipad icons" style="border: 0; max-width: 100%;"></a></li>
      <!-- https://dribbble.com/shots/1543899-iPad-icons -->

      <li><a href="{% static 'galery/img/item03@2x.jpg' %}" title="Mobile Profile"><img src="{% static 'galery/img/item03.jpg' %}" alt="mobile iphone app profile ui" style="border: 0; max-width: 100%;"></a></li>
      <!-- https://dribbble.com/shots/1543085-Profile -->

    </ul>
  </div>
<script type="text/javascript">
$(function(){
  $('#portfolio').magnificPopup({
    delegate: 'a',
    type: 'image',
    image: {
      cursor: null,
      titleSrc: 'title'
    },
    gallery: {
      enabled: true,
      preload: [0,1], // Will preload 0 - before current, and 1 after the current image
      navigateByImgClick: true
		}
  });
});
</script>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kulbeer's Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}
    {% endblock head%}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'posts:list' %}">Kulbeer's Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_superuser %}
                    <li>
                        <a href="{% url 'posts:create' %}">Create Post</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'posts:about' %}">About Me</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->


    <!-- Main Content -->

        {% block content %}


        {% endblock content %}


    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h4 style="text-align:center;">Follow me on...</h4>
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://www.youtube.com/channel/UCY4Z08rzkamLX4Mkf7noFrQ">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/kulbeer.chopra.5">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/killer_kulbeer/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery
    <script src="{% static "js/jquery.js" %}"></script>
-->
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/clean-blog.min.js" %}"></script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

</body>

</html>

templates/base1.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kulbeer's Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  
    <!-- Main Content -->

        {% block content %}


        {% endblock content %}


    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/clean-blog.min.js" %}"></script>

</body>

</html>

templates/postcreate.html
{% extends "base1.html" %}
{% load crispy_forms_tags%}
{% block content %}

<div class="col-sm-6 col-sm-offset-3" >

  <h1>Create a Post</h1>

  <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Create Post">
  </form>

</div>

{% endblock %}

templates/postdetail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<header class="intro-header" style="background-color: #562b47;">

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading" style="padding-top:100px;padding-bottom:50px">
                        <h1>{{ instance.title }}</h1>
                        <span class="meta">{{ instance.timestamp }}</span>
                    </div>
                </div>
            </div>
        </div>
</header>


{% if instance.imageurl %}

<!--
<header class="intro-header" style="background-image: url({{ instance.image.url }})">
-->
  <article>
      <div class="container" style="align:center;">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                  <img src="{{ instance.imageurl }}" >

              </div>
          </div>
      </div>
  </article>

{% else %}
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                    {{ instance.content|linebreaks }}

                </div>
            </div>
        </div>
    </article>

{% endif %}

    <hr>

    <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <div class="fb-like" data-href="{{ instance.get_absolute_url }}"
                      data-layout="standard" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
                    {% if  request.user.is_superuser %}
                    <a href = "{{ instance.get_absolute_url }}edit">
                      <button type="submit" class="btn btn-default" align:"right">Edit</button>
                    </a>
                    <a href = "{{ instance.get_absolute_url }}delete">
                      <button type="submit" class="btn btn-default" align:"right">Delete</button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>



{% endblock %}

templates/postedit.html
{% extends "base1.html" %}
{% load crispy_forms_tags%}
{% block content %}

<div class="col-sm-6 col-sm-offset-3" >

  <h1>Edit</h1>

  <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Edit Post">
  </form>

</div>

{% endblock %}

templates/postlist.html

{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-color: #562b47">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Kulbeer's Blog</h1>
                        <hr class="small">
                        <span class="subheading">A destination for the best short stories</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
 <!-- Main Content -->
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for obj in objlist %}
                {% if obj.imageurl %}
                <div class="post-preview">
                    <a href="{{ obj.get_absolute_url }}">
                        <h2 class="post-title">
                           {{ obj.title }}
                        </h2>
                        <img src="{{ obj.imageurl }}" >
                    </a>
                    <p class="post-meta">{{ obj.timestamp }}</p>
                </div>
                {% else %}
                <div class="post-preview">
                    <a href="{{ obj.get_absolute_url }}">
                        <h2 class="post-title">
                           {{ obj.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ obj.content | linebreaks }}
                        </h3>
                    </a>
                    <p class="post-meta">{{ obj.timestamp }}</p>
                </div>
                <hr>
                {% endif %}
                {% endfor %}
                              <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                      {% if objlist.has_next %}
                        <a href="?page={{ objlist.next_page_number }}">Older Posts &rarr;</a>
                      {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>


{% endblock %}